id: IFF5BFAFD
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T14:50:50+00:00'
last_modified: '2022-06-08T09:05:26.768930+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN7540
  title: རིགས་ལྔ་བདེ་གཤེགས་བསྡུས་པའི་ཚོམ་བུ་ཚོགས་སུ་སྒྲུབ་པའི་ལག་ལེན་ཉེར་མཁོ་ཉིན་བྱེད་སྣང་བ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    A184:
      image_group_id: I3CN7542
      title: ''
      total_pages: 709
      order: 1
      base_file: A184.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
