id: opecha:P009166
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN7540
  title: རིགས་ལྔ་བདེ་གཤེགས་བསྡུས་པའི་ཚོམ་བུ་ཚོགས་སུ་སྒྲུབ་པའི་ལག་ལེན་ཉེར་མཁོ་ཉིན་བྱེད་སྣང་བ།
  volume: ''
  author: ''
